version: v1alpha4
clusters:
  - name: hub
    stage: local
    type: hub
    dnsName: 172.19.0.2.traefik.me
    ssoOrg: local
    ssoTeam: local
    ingressClassName: traefik
    argocd:
      selfManaged: enabled
      repo:
        https:
          configs:
            url: https://github.com/drgeb/kubara-hub-and-spoke-demo.git
            targetRevision: main
          components:
            url: https://github.com/drgeb/kubara-hub-and-spoke-demo.git
            targetRevision: main
    catalogs:
      - ./catalogs/general
      - ./catalogs/platform-engineering
      - ./catalogs/backing-services
    services:
      apicurio:
        status: disabled
      cert-manager:
        status: enabled
        config:
          clusterIssuer:
            email: developer@drgeb.com
            name: letsencrypt-staging
            server: https://acme-staging-v02.api.letsencrypt.org/directory
      external-dns:
        status: disabled
      external-secrets:
        status: enabled
      forgejo:
        status: disabled
      harbor:
        status: disabled
      homer-dashboard:
        status: enabled
      kafka:
        status: disabled
      kargo:
        status: disabled
      keycloak:
        status: disabled
      kube-prometheus-stack:
        status: enabled
      kyverno:
        status: disabled
      kyverno-policies:
        status: disabled
      kyverno-policy-reporter:
        status: disabled
      loki:
        status: disabled
      longhorn:
        status: disabled
      metallb:
        status: disabled
      metrics-server:
        status: enabled
      nexus:
        status: disabled
      oauth2-proxy:
        status: disabled
      ollama:
        status: disabled
      opa:
        status: disabled
      openproject:
        status: disabled
      postgresql:
        status: disabled
      postgresql19:
        status: disabled
      reloader:
        status: disabled
      traefik:
        status: enabled
      uptime-kuma:
        status: disabled
      velero:
        status: disabled
        config:
          backupMode: fs-backup
          backupStorage:
            create: true
            region: eu01
  - name: kubara-spoke-1
    stage: platform-engineering
    type: spoke
    dnsName: spoke-1.kubara.test
    ingressClassName: traefik
    argocd:
      selfManaged: disabled
      config:
        destination:
          server: https://kubara-spoke-1-control-plane:6443
        secretName: kubara-spoke-1-cluster-secret
    catalogs:
      - ./catalogs/platform-engineering
      - ./catalogs/backing-services
      - oci://ghcr.io/kubara-io/catalogs/general:2.0.0
    services:
      apicurio:
        status: enabled
        config:
          database:
            host: postgresql.postgresql.svc.cluster.local
            name: apicurio
            port: 5432
            username: apicurio
          image:
            tag: 2.5.9.Final
          sync:
            enabled: false
      cert-manager:
        status: enabled
        config:
          clusterIssuer:
            email: developer@drgeb.com
            name: letsencrypt-staging
            server: https://acme-staging-v02.api.letsencrypt.org/directory
      external-dns:
        status: disabled
      external-secrets:
        status: enabled
      forgejo:
        status: enabled
        config:
          admin:
            email: admin@local
            username: gitea_admin
          database:
            host: postgresql.postgresql.svc.cluster.local
            name: forgejo
            user: app
          tls:
            enabled: true
            issuerRef:
              kind: ClusterIssuer
              name: kubara-local-ca-issuer
      harbor:
        status: enabled
        config:
          additionalHosts:
            - my.harbor.me
          adminPassword: Harbor12345
          databasePassword: changeit
          hostname: harbor.spoke-1.kubara.test
          networking:
            annotations: {}
          persistence:
            databaseSize: 1Gi
            redisSize: 1Gi
            registrySize: 10Gi
            storageClass: ""
          tls:
            enabled: true
            issuerRef:
              kind: ClusterIssuer
              name: kubara-local-ca-issuer
          tlsCertSource: auto
      kafka:
        status: disabled
      kargo:
        status: enabled
        config:
          integrations:
            argocd: true
            rollouts: true
          tls:
            enabled: true
            issuerRef:
              kind: ClusterIssuer
              name: kubara-local-ca-issuer
      keycloak:
        status: enabled
        config:
          adminUser: admin
          database:
            host: postgresql.postgresql.svc.cluster.local
            name: keycloak
            port: 5432
            username: keycloak
          replicas: 1
      kube-prometheus-stack:
        status: disabled
      kyverno:
        status: disabled
      kyverno-policies:
        status: disabled
      kyverno-policy-reporter:
        status: disabled
      loki:
        status: disabled
      longhorn:
        status: disabled
      metallb:
        status: disabled
      metrics-server:
        status: disabled
      nexus:
        status: enabled
        config:
          tls:
            enabled: true
            issuerRef:
              kind: ClusterIssuer
              name: kubara-local-ca-issuer
      oauth2-proxy:
        status: disabled
      ollama:
        status: disabled
      opa:
        status: enabled
        config:
          replicas: 1
      openproject:
        status: enabled
        config:
          adminEmail: admin@example.com
          adminName: OpenProject Administrator
          database:
            host: postgresql.postgresql.svc.cluster.local
            name: openproject
            port: 5432
            username: openproject
          replicas: 1
          storage:
            size: 20Gi
      postgresql:
        status: enabled
        config:
          database:
            name: forgejo
            username: app
          persistence:
            size: 20Gi
            storageClass: ""
      postgresql19:
        status: disabled
      reloader:
        status: disabled
      traefik:
        status: enabled
      uptime-kuma:
        status: disabled
      velero:
        status: disabled
        config:
          backupMode: fs-backup
          backupStorage:
            create: true
            region: eu01
  - name: kubara-spoke-2
    stage: poc
    type: spoke
    dnsName: spoke-2.kubara.test
    ingressClassName: traefik
    argocd:
      selfManaged: disabled
      config:
        destination:
          server: https://kubara-spoke-2-control-plane:6443
        secretName: kubara-spoke-2-cluster-secret
    catalogs:
      - ./catalogs/backing-services
      - oci://ghcr.io/kubara-io/catalogs/general:2.0.0
    services:
      cert-manager:
        status: disabled
        config:
          clusterIssuer:
            email: developer@drgeb.com
            name: letsencrypt-staging
            server: https://acme-staging-v02.api.letsencrypt.org/directory
      external-dns:
        status: disabled
      external-secrets:
        status: enabled
      kafka:
        status: enabled
        config:
          name: my-kafka
          persistence:
            size: 10Gi
            storageClass: ""
          replicas: 1
          version: ""
      kube-prometheus-stack:
        status: disabled
      kyverno:
        status: disabled
      kyverno-policies:
        status: disabled
      kyverno-policy-reporter:
        status: disabled
      loki:
        status: disabled
      longhorn:
        status: disabled
      metallb:
        status: disabled
      metrics-server:
        status: disabled
      oauth2-proxy:
        status: disabled
      ollama:
        status: enabled
        config:
          models:
            - llama3.2
          storageSize: 30Gi
      postgresql:
        status: enabled
        config:
          database:
            name: app
            username: app
          persistence:
            size: 8Gi
            storageClass: ""
      postgresql19:
        status: enabled
        config:
          database:
            name: app
            username: app
          imageName: ghcr.io/cloudnative-pg/postgresql:19beta2-standard-trixie
          instanceName: postgresql19
          instances: 1
          persistence:
            size: 8Gi
            storageClass: ""
      reloader:
        status: disabled
      traefik:
        status: enabled
      uptime-kuma:
        status: enabled
        networking:
          annotations:
            cert-manager.io/cluster-issuer: kubara-local-ca-issuer
      velero:
        status: disabled
        config:
          backupMode: fs-backup
          backupStorage:
            create: true
            region: eu01
  - name: kubara-dev
    stage: dev
    type: spoke
    dnsName: dev.kubara.test
    ingressClassName: traefik
    argocd:
      selfManaged: disabled
      config:
        destination:
          server: https://kubara-dev-control-plane:6443
        secretName: kubara-dev-cluster-secret
    catalogs:
      - ./catalogs/backing-services
      - oci://ghcr.io/kubara-io/catalogs/general:2.0.0
    services:
      cert-manager:
        status: enabled
        config:
          clusterIssuer:
            email: yourname@your-domain.de
            name: letsencrypt-staging
            server: https://acme-staging-v02.api.letsencrypt.org/directory
      external-dns:
        status: disabled
      external-secrets:
        status: enabled
      kafka:
        status: disabled
      kube-prometheus-stack:
        status: disabled
      kyverno:
        status: disabled
      kyverno-policies:
        status: disabled
      kyverno-policy-reporter:
        status: disabled
      loki:
        status: disabled
      longhorn:
        status: disabled
      metallb:
        status: disabled
      metrics-server:
        status: disabled
      oauth2-proxy:
        status: disabled
      ollama:
        status: disabled
      postgresql:
        status: enabled
        config:
          database:
            name: app
            username: app
          persistence:
            size: 8Gi
            storageClass: ""
      postgresql19:
        status: disabled
      reloader:
        status: disabled
      traefik:
        status: enabled
      uptime-kuma:
        status: disabled
      velero:
        status: disabled
        config:
          backupMode: fs-backup
          backupStorage:
            create: true
            region: eu01
  - name: kubara-staging
    stage: staging
    type: spoke
    dnsName: staging.kubara.test
    ingressClassName: traefik
    argocd:
      selfManaged: disabled
      config:
        destination:
          server: https://kubara-staging-control-plane:6443
        secretName: kubara-staging-cluster-secret
    catalogs:
      - ./catalogs/backing-services
      - oci://ghcr.io/kubara-io/catalogs/general:2.0.0
    services:
      cert-manager:
        status: enabled
        config:
          clusterIssuer:
            email: yourname@your-domain.de
            name: letsencrypt-staging
            server: https://acme-staging-v02.api.letsencrypt.org/directory
      external-dns:
        status: disabled
      external-secrets:
        status: enabled
      kafka:
        status: disabled
      kube-prometheus-stack:
        status: disabled
      kyverno:
        status: disabled
      kyverno-policies:
        status: disabled
      kyverno-policy-reporter:
        status: disabled
      loki:
        status: disabled
      longhorn:
        status: disabled
      metallb:
        status: disabled
      metrics-server:
        status: disabled
      oauth2-proxy:
        status: disabled
      ollama:
        status: disabled
      postgresql:
        status: enabled
        config:
          database:
            name: app
            username: app
          persistence:
            size: 8Gi
            storageClass: ""
      postgresql19:
        status: disabled
      reloader:
        status: disabled
      traefik:
        status: enabled
      uptime-kuma:
        status: disabled
      velero:
        status: disabled
        config:
          backupMode: fs-backup
          backupStorage:
            create: true
            region: eu01
  - name: kubara-prod
    stage: prod
    type: spoke
    dnsName: prod.kubara.test
    ingressClassName: traefik
    argocd:
      selfManaged: disabled
      config:
        destination:
          server: https://kubara-prod-control-plane:6443
        secretName: kubara-prod-cluster-secret
    catalogs:
      - ./catalogs/backing-services
      - oci://ghcr.io/kubara-io/catalogs/general:2.0.0
    services:
      cert-manager:
        status: enabled
        config:
          clusterIssuer:
            email: yourname@your-domain.de
            name: letsencrypt-staging
            server: https://acme-staging-v02.api.letsencrypt.org/directory
      external-dns:
        status: disabled
      external-secrets:
        status: enabled
      kafka:
        status: disabled
      kube-prometheus-stack:
        status: disabled
      kyverno:
        status: disabled
      kyverno-policies:
        status: disabled
      kyverno-policy-reporter:
        status: disabled
      loki:
        status: disabled
      longhorn:
        status: disabled
      metallb:
        status: disabled
      metrics-server:
        status: disabled
      oauth2-proxy:
        status: disabled
      ollama:
        status: disabled
      postgresql:
        status: enabled
        config:
          database:
            name: app
            username: app
          persistence:
            size: 8Gi
            storageClass: ""
      postgresql19:
        status: disabled
      reloader:
        status: disabled
      traefik:
        status: enabled
      uptime-kuma:
        status: disabled
      velero:
        status: disabled
        config:
          backupMode: fs-backup
          backupStorage:
            create: true
            region: eu01
