apiVersion: kubara.io/v1alpha1
kind: ServiceDefinition
metadata:
  name: opa
spec:
  chartPath: opa
  clusterTypes:
  - hub
  - spoke
  status: disabled
  configSchema:
    type: object
    properties:
      hostname:
        type: string
      replicas:
        type: integer
