traefik:
  api:
    basePath: /traefik
  ingressRoute:
    dashboard:
      enabled: true
      entryPoints:
        - websecure
      matchRule: Host(`hub.kubara.test`) && PathPrefix(`/traefik`)
      tls: {}
  service:
    spec:
      loadBalancerIP: 172.19.0.20
