{{- $dbPassword := .Values.postgresql.auth.password | default "" }}
apiVersion: v1
kind: Secret
metadata:
  name: openproject-postgresql
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
  postgres-password: ""
  password: {{ $dbPassword | quote }}
