{{- $secretKeyBase := .Values.openproject.secretKeyBase | default "" }}
{{- if $secretKeyBase }}
apiVersion: v1
kind: Secret
metadata:
  name: openproject-secret-key-base
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
  secret-key-base: {{ $secretKeyBase | quote }}
{{- end }}
