apiVersion: kubara.io/v1alpha1
kind: ServiceDefinition
metadata:
  name: ollama
spec:
  chartPath: ollama
  clusterTypes:
  - hub
  - spoke
  status: disabled
  configSchema:
    type: object
    properties:
      host:
        type: string
      storageSize:
        type: string
      models:
        type: array
        items:
          type: string